//------------------------------------------------------------------
// file name cddefs.h 
// Contains all typedefs and constant objects for all jukebox classes
//------------------------------------------------------------------
#ifndef CDDEFS_H
#define CDDEFS_H

typedef string studentIdType;

typedef long seconds;

const int DEFAULT_NUMBER_OF_TRACKS = 10;

const string CD_FILE_NAME = "cd.dat";

const int DEFAULT_NUMBER_OF_CDS = 200;

#endif