#include <iostream.h> // For cout
#include "baccount" // For the bankAccount class

int main()
{
  bankAccount b1("B. Kreible");     // -a
  bankAccount b2(500.00);           // -b
  BankAccount b3("N. Li", 200.00);  // -c
  b1.deposit();                     // -d
  b1.deposit;                       // -e
  b1.deposit("100.00");             // -f
  B1.deposit(100.00);               // -g
  b1.Deposit(100.00);               // -h
  withdraw(100);                    // -i
  cout << b4.name() << endl;        // -j
  cout << b1.name << endl;          // -k
  cout << b1.name(100.00) << endl;  // -l
  
  return 0;
}